# Generated by Django 4.2.30 on 2026-05-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='current_balance',
            new_name='savings_goal',
        ),
        migrations.RenameField(
            model_name='grouptransaction',
            old_name='reference_number',
            new_name='gcash_reference',
        ),
        migrations.RenameField(
            model_name='grouptransaction',
            old_name='screenshot_url',
            new_name='gcash_screenshot_url',
        ),
        migrations.RemoveField(
            model_name='group',
            name='goal_amount',
        ),
        migrations.RemoveField(
            model_name='group',
            name='target_date',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='is_active',
        ),
        migrations.AddField(
            model_name='group',
            name='gcash_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='group',
            name='gcash_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='group',
            name='gcash_qr_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='group',
            name='invite_code',
            field=models.CharField(default=123, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='total_saved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_by',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='grouptransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='grouptransaction',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
