# Generated by Django 4.2.30 on 2026-05-04 04:09

from django.db import migrations, models
import groups.models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_rename_current_balance_group_savings_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='invite_code',
            field=models.CharField(default=groups.models.generate_invite_code, max_length=20, unique=True),
        ),
    ]
