# Generated by Django 4.2.30 on 2026-05-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='name',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
